import os

TELEGRAM_TOKEN = os.getenv("TELEGRAM_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")

MAX_SIGNALS = 4

SYMBOLS = [
    "BTC_USDT",
    "ETH_USDT",
    "SOL_USDT",
    "ATOM_USDT",
    "TIA_USDT",
    "RUNE_USDT"
]

TREND_TIMEFRAME = "Hour4"
ENTRY_TIMEFRAME = "Min60"